apiVersion: v1
kind: ConfigMap
metadata:
  name: awseventbridge-config
  namespace: awseventbridge-demo
data:
  KAFKA_BOOTSTRAP_URLS: "shop-cluster-kafka-bootstrap:9092"
  QUARKUS_LOG_LEVEL: "INFO"
  AWS_Default_Region: "us-east-2"