apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbridgeui
  namespace: awseventbridge-demo
  labels:
    app: eventbridgeui
    environment: production
    category: awseventbridge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eventbridgeui
    spec:
      containers:
        - name: eventbridgeui
          env:
            - name: REACT_APP_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awseventbridge-secrets
                  key: REACT_APP_AWS_ACCESS_KEY_ID
            - name: REACT_APP_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awseventbridge-secrets
                  key: REACT_APP_AWS_SECRET_ACCESS_KEY
            - name: REACT_APP_AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: awseventbridge-secrets
                  key: REACT_APP_AWS_REGION
            - name: REACT_APP_EVENT_BUS_NAME
              valueFrom:
                secretKeyRef:
                  name: awseventbridge-secrets
                  key: REACT_APP_EVENT_BUS_NAME
            - name: REACT_APP_IDENTITY_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: awseventbridge-secrets
                  key: REACT_APP_IDENTITY_POOL_ID
            - name: QUARKUS_PROFILE
              value: "prod"
