apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbridgesynccamel
  namespace: awseventbridge-demo
  labels:
    app: eventbridgesynccamel
    environment: production
    category: awseventbridge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eventbridgesynccamel
    spec:
      containers:
        - name: eventbridgesynccamel
          env:
            - name: QUARKUS_PROFILE
              value: "prod"