apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbridgeui
  namespace: awseventbridge-demo
  labels:
    app: eventbridgeui
    environment: production
    category: awseventbridge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eventbridgeui
    spec:
      containers:
        - name: eventbridgeui
          env:
            - name: PGSQL_USER
              valueFrom:
                secretKeyRef:
                  name: systemdb-pguser-systemadmin
                  key: user
            - name: PGSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: systemdb-pguser-systemadmin
                  key: password
            - name: QUARKUS_PROFILE
              value: "prod"
        