apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: awseventbridge-demo
  labels:
    app: kafdrop
spec:
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  selector:
    app: kafdrop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: awseventbridge-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "tg-cluster-kafka-bootstrap:9092"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafdrop
  namespace: awseventbridge-demo
spec:
  to:
    kind: Service
    name: kafdrop
  port:
    targetPort: http
  tls:
    termination: edge