apiVersion: v1
kind: ConfigMap
metadata:
  name: my-connect-configmap
data:
  strimzi-connect.properties: |
    bootstrap.servers=debezium-cluster-kafka-bootstrap:9092
    group.id=debezium-cluster
    key.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter=org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable=false
    value.converter.schemas.enable=false
    config.storage.topic=connect-configs
    offset.storage.topic=connect-offsets
    status.storage.topic=connect-statuses
    config.storage.replication.factor=1
    offset.storage.replication.factor=1
    status.storage.replication.factor=1