apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: debezium-cluster
  namespace: debezium-demo
  labels:
    environment: dev
spec:
  kafka:
    version: "3.9.0"
    controllerReplicas: 3
    config:
      process.roles: "controller,broker"
      controller.listener.names: CONTROLLER
      log.dirs: "/var/lib/kafka/data"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: debezium-cluster-controllers
  namespace: debezium-demo
  labels:
    strimzi.io/cluster: debezium-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: debezium-cluster-brokers
  namespace: debezium-demo
  labels:
    strimzi.io/cluster: debezium-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
---
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaUser
# metadata:
#   name: debezium-user
#   namespace: debezium-demo
#   labels:
#     strimzi.io/cluster: debezium-cluster
# spec:
#   authentication:
#     type: scram-sha-512
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: contract
  labels:
    strimzi.io/cluster: debezium-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824