apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-postgres-web
  namespace: awseventbridge-demo
  labels:
    app: reactive-postgres-web
    environment: production
    category: awseventbridge
spec:
  template:
    spec:
      containers:
       - name: reactive-postgres-web
         env:
            - name: PGSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: droneshop-config
                  key: PGSQL_URL
            - name: PGSQL_USER
              valueFrom:
                secretKeyRef:
                  name: droneshopdb-pguser-droneshopadmin
                  key: user
            - name: PGSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: droneshopdb-pguser-droneshopadmin
                  key: password
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: droneshop-config
                  key: QUARKUS_LOG_LEVEL
            - name: KAFKA_BOOTSTRAP_URLS
              valueFrom:
                configMapKeyRef:
                  name: droneshop-config
                  key: KAFKA_BOOTSTRAP_URLS