apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactivewebupdate
  namespace: debezium-demo
  labels:
    app: reactivewebupdate
    environment: production
    category: debezium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reactivewebupdate
    spec:
      containers:
        - name: reactivewebupdate
          env:
            - name: PGSQL_USER
              valueFrom:
                secretKeyRef:
                  name: systemdb-pguser-systemadmin
                  key: user
            - name: PGSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: systemdb-pguser-systemadmin
                  key: password
            - name: QUARKUS_PROFILE
              value: "prod"